baseURL: https://upskillreskill.netlify.app/
languageCode: en-us
title: Educator Online Learning Platform
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: รายละเอียดเพิ่มเติม
    subtitle: |-
      หลักสูตร "การคิดออกแบบ การโค้ชชิ่ง และการออกแบบชั้นเรียนนวัตกรรม" เพื่อสร้างและยกระดับทักษะการทำงานของบุคลากรทางการศึกษาสำหรับการเรียนรู้ออนไลน์และออฟไลน์
    title: Educator Online Learning Platform
  blog: {}
  contact:
    address:
      - city: City, ST 00000
        country: Country
        street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: example@domain.com
        title: Email
    enable: no
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: คณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย
    enable: yes
    quicklinks:
      - alt: KruRoo @ Edu CU
        text: 'Design: '
        url: https://www.facebook.com/KruRooEduCU
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/Upskill-Reskill-Edu-Chula-108438281469923/
      - icon: fa-graduation-cap
        label: KruRooLMS
        url: https://kruroo.com/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: สมัครเข้าร่วมโครงการ
        url: "https://docs.google.com/forms/d/e/1FAIpQLSdVNA56AeqwoxVfdyA27QLnUr8IP3kHQy__7l-DcIc67MUsvQ/viewform"
    button2:
      - name: Log In to KruRoo LMS
        url: 'https://kruroo.com/'
    links:
      - name: Home
        url: '#'
      - name: แนวคิดของโครงการ
        url: project01.html
      - name: รายละเอียดหลักสูตร/ความรู้เผยแพร่
        url: blogs
      - name: ติดต่อเรา
        url: test.html
    menu: Menu
    subtitle: By EDU CU
    title: Design thinking, coaching, and innovative classroom designing curriculum
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: ที่มาของการกำหนดแนวคิด เหตุผล และวัตถุประสงค์ของหลักสูตร
        title: แนวคิดของโครงการ
        url: project01.html
      - image: pic02.jpg
        subtitle: การกำหนดเนื้อหาสาระและโครงสร้างหลักสูตร
        title: การจัดการเรียนการสอน
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: สมัครเข้าร่วมโครงการ
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: สนใจใช่มั้ย? สมัครเข้าร่วมโครงการกับเราได้ที่นี่
    url: "https://docs.google.com/forms/d/e/1FAIpQLSdVNA56AeqwoxVfdyA27QLnUr8IP3kHQy__7l-DcIc67MUsvQ/viewform"
    
    

